version: "3.7"

services:
  app:
    image: alete89/docker-example
    environment:
      MONGO_URL: "mongodb://mongo/test"
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod --noauth --bind_ip=0.0.0.0
